
--- set trace on .

red in CML : type('1 i) == Integer .
red in CML : type('0 l) == Long .
red in CML : type('1 l) == Long .
red in CML : type(('1 l) + ('2 l)) == Long .
red in CML : type(('1 i) + ('2 l)) == Long .
red in CML : type(('1 l) + ('2 i)) == Long .
red in CML : type(('1 l) + True) == Undefined(InvalidArithmeticExpression) .
red in CML : type(('1 l) and True) == Undefined(InvalidLogicalExpression) .
red in CML : type(('1 l) + ('2 f)) == Undefined(InvalidArithmeticExpression) .
red in CML : type(('1 f) + ('2 f)) == Float .
