
load "../src/cml.maude" .

mod SCENARIO is
  pr CML .

  op flag : -> Expression .
  eq type(flag) = Boolean ? .

  op Book : -> RequiredType .
  op book : -> Expression .
  eq type(book) = Book ? .

  op Product : -> RequiredType .
  op product : -> Expression .
  eq type(product) = Product .
endm

set show stats off .
--- set trace on .
--- show components SCENARIO .
--- show sorts SCENARIO .

red in SCENARIO : type(flag) == Undefined(InvalidTypeDeclaration) .
red in SCENARIO : type(flag or True) == Undefined(InvalidLogicalExpression) .
red in SCENARIO : type(book) == Book ? .
red in SCENARIO : type(book === product) == Boolean .
red in SCENARIO : type(book !== product) == Boolean .
red in SCENARIO : type(book is Product) == Boolean .
red in SCENARIO : type(book isnt Product) == Boolean .
red in SCENARIO : type(book as! Product) == Product .
red in SCENARIO : type(book as? Product) == Undefined(InvalidTypeCast) .
