
load "../src/cml.maude" .

mod SCENARIO is
  pr CML .

  op Book : -> ReferentialType .
  ops book books : -> Expression .
  eq type(book) = Book .
  eq type(books) = Book * .

  op Product : -> ReferentialType .
  ops product products : -> Expression .
  eq type(product) = Product .
  eq type(products) = Product * .

  op Order : -> ReferentialType .
  ops order orders : -> Expression .
  eq type(order) = Order .
  eq type(orders) = Order * .

  eq Book <: Product = true .

  var T : Type .
  ceq Order <: T = false if T =/= Order .
  ceq T <: Order = false if T =/= Order .

  op flag : -> Expression .
  eq type(flag) = Boolean .
endm

set show stats off .
--- set trace on .
--- show components SCENARIO .
--- show sorts SCENARIO .

red in SCENARIO : type(book === product) == Boolean .
red in SCENARIO : type(book !== product) == Boolean .

red in SCENARIO : type(product === book) == Boolean .
red in SCENARIO : type(product !== book) == Boolean .

red in SCENARIO : type(book === order) == Undefined(UnrelatedTypeComparison) .
red in SCENARIO : type(book !== order) == Undefined(UnrelatedTypeComparison) .

red in SCENARIO : type(order === book) == Undefined(UnrelatedTypeComparison) .
red in SCENARIO : type(order !== book) == Undefined(UnrelatedTypeComparison) .

red in SCENARIO : type(book === Boolean) == Undefined(ExpectedReferentialTypeOperands) .
red in SCENARIO : type(book !== Boolean) == Undefined(ExpectedReferentialTypeOperands) .

red in SCENARIO : type(book === Book) == Undefined(ExpectedReferentialTypeOperands) .
red in SCENARIO : type(book !== Book) == Undefined(ExpectedReferentialTypeOperands) .

red in SCENARIO : type(book === flag) == Undefined(ExpectedReferentialTypeOperands) .
red in SCENARIO : type(book !== flag) == Undefined(ExpectedReferentialTypeOperands) .

red in SCENARIO : type(book === books) == Undefined(ExpectedReferentialTypeOperands) .
red in SCENARIO : type(book !== books) == Undefined(ExpectedReferentialTypeOperands) .

red in SCENARIO : type(book === products) == Undefined(ExpectedReferentialTypeOperands) .
red in SCENARIO : type(book !== products) == Undefined(ExpectedReferentialTypeOperands) .

red in SCENARIO : type(book === orders) == Undefined(ExpectedReferentialTypeOperands) .
red in SCENARIO : type(book !== orders) == Undefined(ExpectedReferentialTypeOperands) .

red in SCENARIO : type(book is Product) == Boolean .
red in SCENARIO : type(book isnt Product) == Boolean .

red in SCENARIO : type(book is Product ?) == Boolean .
red in SCENARIO : type(book isnt Product ?) == Boolean .

red in SCENARIO : type(book is Product *) == Boolean .
red in SCENARIO : type(book isnt Product *) == Boolean .

red in SCENARIO : type(product is Book) == Boolean .
red in SCENARIO : type(product isnt Book) == Boolean .

red in SCENARIO : type(product is Book ?) == Boolean .
red in SCENARIO : type(product isnt Book ?) == Boolean .

red in SCENARIO : type(product is Book *) == Boolean .
red in SCENARIO : type(product isnt Book *) == Boolean .

red in SCENARIO : type(book is Order) == Undefined(UnrelatedTypeCheck) .
red in SCENARIO : type(book isnt Order) == Undefined(UnrelatedTypeCheck) .

red in SCENARIO : type(book is Order ?) == Undefined(UnrelatedTypeCheck) .
red in SCENARIO : type(book isnt Order ?) == Undefined(UnrelatedTypeCheck) .

red in SCENARIO : type(book is Order *) == Undefined(UnrelatedTypeCheck) .
red in SCENARIO : type(book isnt Order *) == Undefined(UnrelatedTypeCheck) .

red in SCENARIO : type(book is Boolean) == Undefined(UnrelatedTypeCheck) .
red in SCENARIO : type(book isnt Boolean) == Undefined(UnrelatedTypeCheck) .

red in SCENARIO : type(book is flag) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(book isnt flag) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(book is books) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(book isnt books) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(book is products) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(book isnt products) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(book is orders) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(book isnt orders) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(book as Product) == Product .
red in SCENARIO : type(book as! Product) == Undefined(UnnecessarilyForcedTypeCast) .
red in SCENARIO : type(book as? Product) == Undefined(UnnecessarilyConditionalTypeCast) .

red in SCENARIO : type(book as Product ?) == Product ? .
red in SCENARIO : type(book as! Product ?) == Undefined(UnnecessarilyForcedTypeCast) .
red in SCENARIO : type(book as? Product ?) == Undefined(UnnecessarilyConditionalTypeCast) .

red in SCENARIO : type(book as Product *) == Product * .
red in SCENARIO : type(book as! Product *) == Undefined(UnnecessarilyForcedTypeCast) .
red in SCENARIO : type(book as? Product *) == Undefined(UnnecessarilyConditionalTypeCast) .

red in SCENARIO : type(product as Book) == Undefined(InvalidSubTypeCast) .
red in SCENARIO : type(product as! Book) == Book .
red in SCENARIO : type(product as? Book) == Undefined(InvalidReferentialTypeOperand) .

red in SCENARIO : type(product as Book ?) == Undefined(InvalidSubTypeCast) .
red in SCENARIO : type(product as! Book ?) == Book ? .
red in SCENARIO : type(product as? Book ?) == Book ? .

red in SCENARIO : type(product as Book *) == Undefined(InvalidSubTypeCast) .
red in SCENARIO : type(product as! Book *) == Book * .
red in SCENARIO : type(product as? Book *) == Book * .

red in SCENARIO : type(book as flag) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(book as! flag) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(book as? flag) == Undefined(ExpectedTypeCastOperand) .

red in SCENARIO : type(book as products) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(book as! products) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(book as? products) == Undefined(ExpectedTypeCastOperand) .

red in SCENARIO : type(book as orders) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(book as! orders) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(book as? orders) == Undefined(ExpectedTypeCastOperand) .
