
load "../src/cml.maude" .

mod SCENARIO is
  pr CML .

  op flag : -> Expression .
  eq type(flag) = Boolean * .

  op Book : -> RequiredType .
  op books : -> Expression .
  eq type(books) = Book * .

  op Product : -> RequiredType .
  op product : -> Expression .
  eq type(product) = Product .
endm

set show stats off .
--- set trace on .
--- show components SCENARIO .
--- show sorts SCENARIO .

red in SCENARIO : type(flag) == Undefined(InvalidSequentialTypeDeclaration) .
red in SCENARIO : type(flag or True) == Undefined(InvalidLogicalExpression) .
red in SCENARIO : type(books) == Book * .
red in SCENARIO : type(books === books) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books === product) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books !== books) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books !== product) == Undefined(InvalidReferentialExpression) .
--- red in SCENARIO : type(books is Product *) == Boolean .
--- red in SCENARIO : type(books is Product ?) == Boolean .
--- red in SCENARIO : type(books is Product) == Boolean .
--- red in SCENARIO : type(books is Product *) == Boolean .
--- red in SCENARIO : type(books is Product ?) == Boolean .
--- red in SCENARIO : type(books is Product) == Boolean .
red in SCENARIO : type(books as! Product) == Product .
red in SCENARIO : type(books as! Product ?) == Product ? .
red in SCENARIO : type(books as! Product *) == Product * .
red in SCENARIO : type(books as? Product *) == Product * .
red in SCENARIO : type(books as? Product ?) == Undefined(InvalidOptionalTypeCast)  .
red in SCENARIO : type(books as? Product) == Undefined(InvalidRequiredTypeCast) .
red in SCENARIO : type(books === flag) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books !== flag) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books is flag) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books isnt flag) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books as! flag) == Undefined(InvalidReferentialExpression) .
red in SCENARIO : type(books as? flag) == Undefined(InvalidReferentialExpression) .
