
--- set trace on .
--- show components SCENARIO .
--- show sorts SCENARIO .

red in SCENARIO : type(books === product) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== product) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(product === books) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(product !== books) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books === order) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== order) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(order === books) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(order !== books) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books === Boolean) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== Boolean) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books === Book) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== Book) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books === flag) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== flag) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books === book) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== book) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books === products) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== products) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books === orders) == Undefined(ExpectedReferenceTypeOperands) .
red in SCENARIO : type(books !== orders) == Undefined(ExpectedReferenceTypeOperands) .

red in SCENARIO : type(books is Product) == Undefined(OutOfBoundsTypeCheck) .
red in SCENARIO : type(books isnt Product) == Undefined(OutOfBoundsTypeCheck) .

red in SCENARIO : type(books is Product ?) == Undefined(OutOfBoundsTypeCheck) .
red in SCENARIO : type(books isnt Product ?) == Undefined(OutOfBoundsTypeCheck) .

red in SCENARIO : type(book is Product *) == Boolean .
red in SCENARIO : type(book isnt Product *) == Boolean .

red in SCENARIO : type(products is Book) == Undefined(OutOfBoundsTypeCheck) .
red in SCENARIO : type(products isnt Book) == Undefined(OutOfBoundsTypeCheck) .

red in SCENARIO : type(products is Book ?) == Undefined(OutOfBoundsTypeCheck) .
red in SCENARIO : type(products isnt Book ?) == Undefined(OutOfBoundsTypeCheck) .

red in SCENARIO : type(products is Book *) == Boolean .
red in SCENARIO : type(products isnt Book *) == Boolean .

red in SCENARIO : type(books is Order) == Undefined(OutOfBoundsTypeCheck) .
red in SCENARIO : type(books isnt Order) == Undefined(OutOfBoundsTypeCheck) .

red in SCENARIO : type(books is Order ?) == Undefined(OutOfBoundsTypeCheck) .
red in SCENARIO : type(books isnt Order ?) == Undefined(OutOfBoundsTypeCheck) .

red in SCENARIO : type(books is Order *) == Undefined(UnrelatedTypeCheck) .
red in SCENARIO : type(books isnt Order *) == Undefined(UnrelatedTypeCheck) .

red in SCENARIO : type(books is Boolean) == Undefined(OutOfBoundsTypeCheck) .
red in SCENARIO : type(books isnt Boolean) == Undefined(OutOfBoundsTypeCheck) .

red in SCENARIO : type(books is flag) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(books isnt flag) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(books is books) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(books isnt books) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(books is products) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(books isnt products) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(books is orders) == Undefined(ExpectedTypeCheckOperand) .
red in SCENARIO : type(books isnt orders) == Undefined(ExpectedTypeCheckOperand) .

red in SCENARIO : type(books as Product) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(books as! Product) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(books as? Product) == Undefined(OutOfBoundsTypeCast) .

red in SCENARIO : type(books as Product ?) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(books as! Product ?) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(books as? Product ?) == Undefined(OutOfBoundsTypeCast) .

red in SCENARIO : type(books as Product *) == Product * .
red in SCENARIO : type(books as! Product *) == Undefined(UnnecessarilyForcedTypeCast) .
red in SCENARIO : type(books as? Product *) == Undefined(UnnecessarilyConditionalTypeCast) .

red in SCENARIO : type(products as Book) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(products as! Book) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(products as? Book) == Undefined(OutOfBoundsTypeCast) .

red in SCENARIO : type(products as Book ?) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(products as! Book ?) == Undefined(OutOfBoundsTypeCast) .
red in SCENARIO : type(products as? Book ?) == Undefined(OutOfBoundsTypeCast) .

red in SCENARIO : type(products as Book *) == Undefined(InvalidSubTypeCast) .
red in SCENARIO : type(products as! Book *) == Book * .
red in SCENARIO : type(products as? Book *) == Book * .

red in SCENARIO : type(books as flag) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(books as! flag) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(books as? flag) == Undefined(ExpectedTypeCastOperand) .

red in SCENARIO : type(books as products) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(books as! products) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(books as? products) == Undefined(ExpectedTypeCastOperand) .

red in SCENARIO : type(books as orders) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(books as! orders) == Undefined(ExpectedTypeCastOperand) .
red in SCENARIO : type(books as? orders) == Undefined(ExpectedTypeCastOperand) .
