
red in SCENARIO : (Boolean *) == (Boolean *) .
red in SCENARIO : (Boolean * *) == Undefined(InvalidCardinalityDeclaration) .

red in SCENARIO : (Boolean ?) == (Boolean ?) .
red in SCENARIO : (Boolean ? ?) == Undefined(InvalidCardinalityDeclaration) .

red in SCENARIO : (Boolean ? *) == Undefined(InvalidCardinalityDeclaration) .
red in SCENARIO : (Boolean * ?) == Undefined(InvalidCardinalityDeclaration) .
